# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 778)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sideBarLayout = QtWidgets.QVBoxLayout()
        self.sideBarLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.sideBarLayout.setObjectName("sideBarLayout")
        self.openButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        self.openButton.setMaximumSize(QtCore.QSize(60, 60))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/black/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/white/open.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/white/open.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.openButton.setIcon(icon)
        self.openButton.setIconSize(QtCore.QSize(48, 48))
        self.openButton.setObjectName("openButton")
        self.sideBarLayout.addWidget(self.openButton, 0, QtCore.Qt.AlignLeft)
        self.saveButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMaximumSize(QtCore.QSize(60, 60))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/black/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/white/save.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/white/save.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon1)
        self.saveButton.setIconSize(QtCore.QSize(48, 48))
        self.saveButton.setObjectName("saveButton")
        self.sideBarLayout.addWidget(self.saveButton, 0, QtCore.Qt.AlignLeft)
        self.connectButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(0, 0))
        self.connectButton.setMaximumSize(QtCore.QSize(60, 60))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/black/connect1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/white/connect1.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/white/connect1.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.connectButton.setIcon(icon2)
        self.connectButton.setIconSize(QtCore.QSize(48, 48))
        self.connectButton.setObjectName("connectButton")
        self.sideBarLayout.addWidget(self.connectButton, 0, QtCore.Qt.AlignLeft)
        self.disconnectButton = QtWidgets.QToolButton(self.centralwidget)
        self.disconnectButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnectButton.sizePolicy().hasHeightForWidth())
        self.disconnectButton.setSizePolicy(sizePolicy)
        self.disconnectButton.setMaximumSize(QtCore.QSize(60, 60))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/black/disconnect1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/white/disconnect1.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/white/disconnect1.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.disconnectButton.setIcon(icon3)
        self.disconnectButton.setIconSize(QtCore.QSize(48, 48))
        self.disconnectButton.setObjectName("disconnectButton")
        self.sideBarLayout.addWidget(self.disconnectButton, 0, QtCore.Qt.AlignLeft)
        self.startSdButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startSdButton.sizePolicy().hasHeightForWidth())
        self.startSdButton.setSizePolicy(sizePolicy)
        self.startSdButton.setMaximumSize(QtCore.QSize(60, 60))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/black/sdstart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icons/white/sdstart.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icons/white/sdstop.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.startSdButton.setIcon(icon4)
        self.startSdButton.setIconSize(QtCore.QSize(48, 48))
        self.startSdButton.setObjectName("startSdButton")
        self.sideBarLayout.addWidget(self.startSdButton, 0, QtCore.Qt.AlignLeft)
        self.stopSdButton = QtWidgets.QToolButton(self.centralwidget)
        self.stopSdButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopSdButton.sizePolicy().hasHeightForWidth())
        self.stopSdButton.setSizePolicy(sizePolicy)
        self.stopSdButton.setMaximumSize(QtCore.QSize(60, 60))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/black/sdstop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icons/white/sdstop.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icons/white/sdstop.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.stopSdButton.setIcon(icon5)
        self.stopSdButton.setIconSize(QtCore.QSize(48, 48))
        self.stopSdButton.setObjectName("stopSdButton")
        self.sideBarLayout.addWidget(self.stopSdButton, 0, QtCore.Qt.AlignLeft)
        self.transmitButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transmitButton.sizePolicy().hasHeightForWidth())
        self.transmitButton.setSizePolicy(sizePolicy)
        self.transmitButton.setMaximumSize(QtCore.QSize(60, 60))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/black/transmit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/white/transmit.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/white/transmit.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.transmitButton.setIcon(icon6)
        self.transmitButton.setIconSize(QtCore.QSize(48, 48))
        self.transmitButton.setObjectName("transmitButton")
        self.sideBarLayout.addWidget(self.transmitButton, 0, QtCore.Qt.AlignLeft)
        self.retransmitButton = QtWidgets.QToolButton(self.centralwidget)
        self.retransmitButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.retransmitButton.sizePolicy().hasHeightForWidth())
        self.retransmitButton.setSizePolicy(sizePolicy)
        self.retransmitButton.setMinimumSize(QtCore.QSize(60, 60))
        self.retransmitButton.setMaximumSize(QtCore.QSize(60, 60))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/black/retransmit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/white/retransmit.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/white/retransmit.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.retransmitButton.setIcon(icon7)
        self.retransmitButton.setIconSize(QtCore.QSize(32, 32))
        self.retransmitButton.setObjectName("retransmitButton")
        self.sideBarLayout.addWidget(self.retransmitButton, 0, QtCore.Qt.AlignLeft)
        self.markButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.markButton.sizePolicy().hasHeightForWidth())
        self.markButton.setSizePolicy(sizePolicy)
        self.markButton.setMaximumSize(QtCore.QSize(60, 60))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/black/mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/white/mark.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/white/mark.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.markButton.setIcon(icon8)
        self.markButton.setIconSize(QtCore.QSize(32, 32))
        self.markButton.setObjectName("markButton")
        self.sideBarLayout.addWidget(self.markButton)
        self.horizontalLayout_2.addLayout(self.sideBarLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.traceTab = QtWidgets.QWidget()
        self.traceTab.setObjectName("traceTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.traceTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.traceTab, "")
        self.rxtxTab = QtWidgets.QWidget()
        self.rxtxTab.setObjectName("rxtxTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.rxtxTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget.addTab(self.rxtxTab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFile_2 = QtWidgets.QAction(MainWindow)
        self.actionFile_2.setObjectName("actionFile_2")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CAN-D Data Logger"))
        self.saveButton.setText(_translate("MainWindow", "..."))
        self.connectButton.setText(_translate("MainWindow", "..."))
        self.disconnectButton.setText(_translate("MainWindow", "..."))
        self.startSdButton.setText(_translate("MainWindow", "..."))
        self.stopSdButton.setText(_translate("MainWindow", "..."))
        self.transmitButton.setText(_translate("MainWindow", "..."))
        self.retransmitButton.setText(_translate("MainWindow", "..."))
        self.markButton.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.traceTab), _translate("MainWindow", "Trace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rxtxTab), _translate("MainWindow", "Receive/Transmit"))
        self.actionFile_2.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As ..."))


from widgets import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
