# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner/transmitmessage.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 778)
        self.transmitBox = QtWidgets.QGroupBox(Form)
        self.transmitBox.setGeometry(QtCore.QRect(14, 10, 560, 693))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.transmitBox.setFont(font)
        self.transmitBox.setObjectName("transmitBox")
        self.dataTransmitBox = QtWidgets.QGroupBox(self.transmitBox)
        self.dataTransmitBox.setGeometry(QtCore.QRect(10, 170, 291, 71))
        self.dataTransmitBox.setObjectName("dataTransmitBox")
        self.databyte_13_14 = QtWidgets.QPlainTextEdit(self.dataTransmitBox)
        self.databyte_13_14.setGeometry(QtCore.QRect(220, 30, 23, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.databyte_13_14.setFont(font)
        self.databyte_13_14.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.databyte_13_14.setObjectName("databyte_13_14")
        self.label6 = QtWidgets.QLabel(self.dataTransmitBox)
        self.label6.setGeometry(QtCore.QRect(190, 50, 23, 21))
        self.label6.setAlignment(QtCore.Qt.AlignCenter)
        self.label6.setObjectName("label6")
        self.label5 = QtWidgets.QLabel(self.dataTransmitBox)
        self.label5.setGeometry(QtCore.QRect(160, 50, 23, 21))
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setObjectName("label5")
        self.databyte_0_1 = QtWidgets.QPlainTextEdit(self.dataTransmitBox)
        self.databyte_0_1.setGeometry(QtCore.QRect(10, 30, 23, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.databyte_0_1.setFont(font)
        self.databyte_0_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.databyte_0_1.setObjectName("databyte_0_1")
        self.databyte_9_10 = QtWidgets.QPlainTextEdit(self.dataTransmitBox)
        self.databyte_9_10.setGeometry(QtCore.QRect(160, 30, 23, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.databyte_9_10.setFont(font)
        self.databyte_9_10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.databyte_9_10.setObjectName("databyte_9_10")
        self.databyte_7_8 = QtWidgets.QPlainTextEdit(self.dataTransmitBox)
        self.databyte_7_8.setGeometry(QtCore.QRect(130, 30, 23, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.databyte_7_8.setFont(font)
        self.databyte_7_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.databyte_7_8.setObjectName("databyte_7_8")
        self.databyte_2_3 = QtWidgets.QPlainTextEdit(self.dataTransmitBox)
        self.databyte_2_3.setGeometry(QtCore.QRect(40, 30, 23, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.databyte_2_3.setFont(font)
        self.databyte_2_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.databyte_2_3.setObjectName("databyte_2_3")
        self.label7 = QtWidgets.QLabel(self.dataTransmitBox)
        self.label7.setGeometry(QtCore.QRect(220, 50, 23, 21))
        self.label7.setAlignment(QtCore.Qt.AlignCenter)
        self.label7.setObjectName("label7")
        self.label0 = QtWidgets.QLabel(self.dataTransmitBox)
        self.label0.setGeometry(QtCore.QRect(10, 50, 23, 21))
        self.label0.setAlignment(QtCore.Qt.AlignCenter)
        self.label0.setObjectName("label0")
        self.databyte_6_7 = QtWidgets.QPlainTextEdit(self.dataTransmitBox)
        self.databyte_6_7.setGeometry(QtCore.QRect(100, 30, 23, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.databyte_6_7.setFont(font)
        self.databyte_6_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.databyte_6_7.setObjectName("databyte_6_7")
        self.label4 = QtWidgets.QLabel(self.dataTransmitBox)
        self.label4.setGeometry(QtCore.QRect(130, 50, 23, 21))
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.databyte_4_5 = QtWidgets.QPlainTextEdit(self.dataTransmitBox)
        self.databyte_4_5.setGeometry(QtCore.QRect(70, 30, 23, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.databyte_4_5.setFont(font)
        self.databyte_4_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.databyte_4_5.setObjectName("databyte_4_5")
        self.label1 = QtWidgets.QLabel(self.dataTransmitBox)
        self.label1.setGeometry(QtCore.QRect(40, 50, 23, 21))
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.databyte_11_12 = QtWidgets.QPlainTextEdit(self.dataTransmitBox)
        self.databyte_11_12.setGeometry(QtCore.QRect(190, 30, 23, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.databyte_11_12.setFont(font)
        self.databyte_11_12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.databyte_11_12.setObjectName("databyte_11_12")
        self.label2 = QtWidgets.QLabel(self.dataTransmitBox)
        self.label2.setGeometry(QtCore.QRect(70, 50, 23, 21))
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.dataTransmitBox)
        self.label3.setGeometry(QtCore.QRect(100, 50, 23, 21))
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")
        self.settingsTransmitBox = QtWidgets.QGroupBox(self.transmitBox)
        self.settingsTransmitBox.setGeometry(QtCore.QRect(10, 40, 291, 121))
        self.settingsTransmitBox.setObjectName("settingsTransmitBox")
        self.layoutWidget = QtWidgets.QWidget(self.settingsTransmitBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 471, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.idText = QtWidgets.QPlainTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.idText.setFont(font)
        self.idText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.idText.setObjectName("idText")
        self.gridLayout.addWidget(self.idText, 0, 1, 1, 1)
        self.cycleUnitLabel = QtWidgets.QLabel(self.layoutWidget)
        self.cycleUnitLabel.setObjectName("cycleUnitLabel")
        self.gridLayout.addWidget(self.cycleUnitLabel, 3, 2, 1, 1)
        self.cycleText = QtWidgets.QPlainTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cycleText.setFont(font)
        self.cycleText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cycleText.setObjectName("cycleText")
        self.gridLayout.addWidget(self.cycleText, 3, 1, 1, 1)
        self.idLabel = QtWidgets.QLabel(self.layoutWidget)
        self.idLabel.setObjectName("idLabel")
        self.gridLayout.addWidget(self.idLabel, 0, 0, 1, 1)
        self.lengthLabel = QtWidgets.QLabel(self.layoutWidget)
        self.lengthLabel.setObjectName("lengthLabel")
        self.gridLayout.addWidget(self.lengthLabel, 2, 0, 1, 1)
        self.cycleLabel = QtWidgets.QLabel(self.layoutWidget)
        self.cycleLabel.setObjectName("cycleLabel")
        self.gridLayout.addWidget(self.cycleLabel, 3, 0, 1, 1)
        self.lengthSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lengthSpinBox.setFont(font)
        self.lengthSpinBox.setObjectName("lengthSpinBox")
        self.gridLayout.addWidget(self.lengthSpinBox, 2, 1, 1, 1)
        self.messageTypeTransmitBox = QtWidgets.QGroupBox(self.transmitBox)
        self.messageTypeTransmitBox.setGeometry(QtCore.QRect(10, 250, 291, 121))
        self.messageTypeTransmitBox.setObjectName("messageTypeTransmitBox")
        self.extendedFrameBox = QtWidgets.QCheckBox(self.messageTypeTransmitBox)
        self.extendedFrameBox.setGeometry(QtCore.QRect(10, 30, 271, 20))
        self.extendedFrameBox.setObjectName("extendedFrameBox")
        self.remoteRequestBox = QtWidgets.QCheckBox(self.messageTypeTransmitBox)
        self.remoteRequestBox.setEnabled(False)
        self.remoteRequestBox.setGeometry(QtCore.QRect(10, 50, 271, 20))
        self.remoteRequestBox.setObjectName("remoteRequestBox")
        self.canFDBox = QtWidgets.QCheckBox(self.messageTypeTransmitBox)
        self.canFDBox.setGeometry(QtCore.QRect(10, 70, 271, 20))
        self.canFDBox.setObjectName("canFDBox")
        self.bitRateSwitchBox = QtWidgets.QCheckBox(self.messageTypeTransmitBox)
        self.bitRateSwitchBox.setGeometry(QtCore.QRect(10, 90, 271, 20))
        self.bitRateSwitchBox.setObjectName("bitRateSwitchBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.transmitBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 380, 151, 32))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.buttonLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("buttonLayout")
        self.sendButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.sendButton.setObjectName("sendButton")
        self.buttonLayout.addWidget(self.sendButton)
        self.clearButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.clearButton.setObjectName("clearButton")
        self.buttonLayout.addWidget(self.clearButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.transmitBox.setTitle(_translate("Form", "Transmit Message"))
        self.dataTransmitBox.setTitle(_translate("Form", "Data (hex):"))
        self.label6.setText(_translate("Form", "6"))
        self.label5.setText(_translate("Form", "5"))
        self.label7.setText(_translate("Form", "7"))
        self.label0.setText(_translate("Form", "0"))
        self.label4.setText(_translate("Form", "4"))
        self.label1.setText(_translate("Form", "1"))
        self.label2.setText(_translate("Form", "2"))
        self.label3.setText(_translate("Form", "3"))
        self.settingsTransmitBox.setTitle(_translate("Form", "Settings"))
        self.cycleUnitLabel.setText(_translate("Form", "ms"))
        self.idLabel.setText(_translate("Form", "ID (hex):"))
        self.lengthLabel.setText(_translate("Form", "Length:"))
        self.cycleLabel.setText(_translate("Form", "Cycle:"))
        self.messageTypeTransmitBox.setTitle(_translate("Form", "Message Type"))
        self.extendedFrameBox.setText(_translate("Form", "Extended Frame"))
        self.remoteRequestBox.setText(_translate("Form", "Remote Request"))
        self.canFDBox.setText(_translate("Form", "CAN FD"))
        self.bitRateSwitchBox.setText(_translate("Form", "Bit Rate Switch"))
        self.sendButton.setText(_translate("Form", "Send"))
        self.clearButton.setText(_translate("Form", "Clear"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
