# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner/transmit.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(311, 330)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.windowLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.windowLabel.setFont(font)
        self.windowLabel.setObjectName("windowLabel")
        self.verticalLayout.addWidget(self.windowLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.idForm = QtWidgets.QFormLayout()
        self.idForm.setObjectName("idForm")
        self.idInput = QtWidgets.QTextEdit(Dialog)
        self.idInput.setMaximumSize(QtCore.QSize(100, 25))
        self.idInput.setObjectName("idInput")
        self.idForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.idInput)
        self.idLabel = QtWidgets.QLabel(Dialog)
        self.idLabel.setObjectName("idLabel")
        self.idForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.idLabel)
        self.horizontalLayout.addLayout(self.idForm)
        self.lengthForm = QtWidgets.QFormLayout()
        self.lengthForm.setObjectName("lengthForm")
        self.lengthInput = QtWidgets.QSpinBox(Dialog)
        self.lengthInput.setMinimumSize(QtCore.QSize(45, 0))
        self.lengthInput.setObjectName("lengthInput")
        self.lengthForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lengthInput)
        self.lengthLabel = QtWidgets.QLabel(Dialog)
        self.lengthLabel.setObjectName("lengthLabel")
        self.lengthForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lengthLabel)
        self.horizontalLayout.addLayout(self.lengthForm)
        self.cycleForm = QtWidgets.QFormLayout()
        self.cycleForm.setObjectName("cycleForm")
        self.cycleInput = QtWidgets.QTextEdit(Dialog)
        self.cycleInput.setMaximumSize(QtCore.QSize(75, 25))
        self.cycleInput.setObjectName("cycleInput")
        self.cycleForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cycleInput)
        self.cycleLabel = QtWidgets.QLabel(Dialog)
        self.cycleLabel.setObjectName("cycleLabel")
        self.cycleForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cycleLabel)
        self.msLabel = QtWidgets.QLabel(Dialog)
        self.msLabel.setObjectName("msLabel")
        self.cycleForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.msLabel)
        self.horizontalLayout.addLayout(self.cycleForm)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.dataForm = QtWidgets.QFormLayout()
        self.dataForm.setObjectName("dataForm")
        self.dataInput = QtWidgets.QTextEdit(Dialog)
        self.dataInput.setMinimumSize(QtCore.QSize(267, 0))
        self.dataInput.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dataInput.setObjectName("dataInput")
        self.dataForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dataInput)
        self.dataLabel = QtWidgets.QLabel(Dialog)
        self.dataLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dataLabel.setObjectName("dataLabel")
        self.dataForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dataLabel)
        self.verticalLayout.addLayout(self.dataForm)
        self.msgTypeGroupBox = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.msgTypeGroupBox.setFont(font)
        self.msgTypeGroupBox.setObjectName("msgTypeGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.msgTypeGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.efCheckBox = QtWidgets.QCheckBox(self.msgTypeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.efCheckBox.setFont(font)
        self.efCheckBox.setObjectName("efCheckBox")
        self.verticalLayout_2.addWidget(self.efCheckBox)
        self.rrCheckBox = QtWidgets.QCheckBox(self.msgTypeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.rrCheckBox.setFont(font)
        self.rrCheckBox.setObjectName("rrCheckBox")
        self.verticalLayout_2.addWidget(self.rrCheckBox)
        self.fdCheckBox = QtWidgets.QCheckBox(self.msgTypeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fdCheckBox.setFont(font)
        self.fdCheckBox.setObjectName("fdCheckBox")
        self.verticalLayout_2.addWidget(self.fdCheckBox)
        self.brsCheckBox = QtWidgets.QCheckBox(self.msgTypeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.brsCheckBox.setFont(font)
        self.brsCheckBox.setObjectName("brsCheckBox")
        self.verticalLayout_2.addWidget(self.brsCheckBox)
        self.verticalLayout.addWidget(self.msgTypeGroupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.windowLabel.setText(_translate("Dialog", "Transmit Message"))
        self.idLabel.setText(_translate("Dialog", "ID: (hex)"))
        self.lengthLabel.setText(_translate("Dialog", "Length:"))
        self.cycleLabel.setText(_translate("Dialog", "Cycle"))
        self.msLabel.setText(_translate("Dialog", "ms"))
        self.dataLabel.setText(_translate("Dialog", "Data: (hex)"))
        self.msgTypeGroupBox.setTitle(_translate("Dialog", "Message Type"))
        self.efCheckBox.setText(_translate("Dialog", "Extended Frame"))
        self.rrCheckBox.setText(_translate("Dialog", "Remote Request"))
        self.fdCheckBox.setText(_translate("Dialog", "CAN FD"))
        self.brsCheckBox.setText(_translate("Dialog", "Bit Rate Switch (BRS)"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
