pipeline {
    agent { 
        docker{
            image 'bofrim/arm-none-eabi-gcc_proto-c'
        }
    }

    stages {
        stage('Build') {
            steps {
                sh 'make clean --file ./CAN-D/Makefile && make --file=CAN-D/Makefile' 
            }
        }
    }
}
